### ISSUE TITLE
Implement the calendar on the calendar page

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#26]
Implement the calendar with the following functionalities:

- [x] Vertically scrollable
- [x] Displays dates from current day to November 2021
- [x] Properly labels the day of the week
- [x] Click on a day will open up an empty page (to be implemented for logging daily symptoms)

**Comment by PierreLessard** [comment]
For navigating to the logging daily symptom page, animated navigation is limited for the normal NavController. In the IOS app the daily symptom log page pops up from the bottom of the screen. Solutions online recommend using AnimatedNavHost. It seems to be simple to migrate. Here are some links with resources or discussions on it:

https://shortcut.io/tech/adding-animations-to-your-jetpack-compose-navigation/
https://google.github.io/accompanist/navigation-animation/

It uses the same Accompanist that I used to add swipeable navigation synced with tabs between the cycle and calendar page. It would be something to consider as during the meeting TPP did mention wanting more animations between pages.

Another current limitation seems to be with OverScrolling. Unfortunately there does not seem to be a simple way to animate OverScroll nicely, such as in the IOS app (excluding the glitch on the settings page). Thankfully this is just a minor aesthetics issue. Here is nice stackoverflow post on this issue:
https://stackoverflow.com/questions/70754397/how-to-implement-bounce-effect-on-jetpack-compose-lazy-column
