### ISSUE TITLE
Find a package for calendar

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#5]
Find a package that we can use to implement the calendar view.

- [x] The calendar view should be scrollable vertically
- [x] We should be able to customize the "on click" behaviour of individual dates
- [x] We should be able to customize the appearance of the calendar

<img width="329" alt="Screen Shot 2022-11-01 at 2 03 15 PM" src="https://user-images.githubusercontent.com/75044178/199305561-8c730d1d-2056-40e8-b8e4-c696bd9f25d1.png">

**Comment by madelahn** [comment]
[Kizitonwose's Calendar](https://github.com/kizitonwose/Calendar) definitely seems like the best option for us from my research: It has a wide range of customizability, offers different functions for adding events to different date(s), and also has a vertical scroll (and horizontal if needed).
Every other Calendar Compose Library/package seems a lot more limited in comparison, and while Compose does have a Calendar abstract class, it will definitely be very difficult to implement from scratch.

Here is a screenshot from the repository's README that looks similar to what we're planning to do
![image](https://user-images.githubusercontent.com/93456777/202878204-b820931d-2639-4c36-ba62-5dab3c527b2e.png)

For now, I will verify that this widget is capable of doing everything we want it to and test it out myself! If there is any feedback, please let me know :)

**Comment by leowrites** [comment]
I think this looks awesome! Great work. Let's look into this more to be sure that we can customize it to do our functionalities.

**Comment by madelahn** [comment]
I've finished setting up the basic calendar setup! It took me a bit to learn since the documentation is a bit vague, but I think I'm getting pretty comfortable with using it right now. Here's what I have so far:
![image](https://im2.ezgif.com/tmp/ezgif-2-135683a28f.gif)

I'm going to try to fully figure out the layout for the calendar by our next meeting to work on it for December.
Let me know your thoughts! Also, if you want me to send the source code, I can do that as well 😃

**Comment by elenawzy** [comment]
Thanks! The image that you sent is actually expired so would you be able to send it again LOL other than that, sounds great!

**Comment by leowrites** [comment]
Perfect! I will make an issue to start the implementation for the calendar, and you can start right away. I asked Kevin and Mann to work with you as they need a calendar for their part as well!

**Comment by madelahn** [comment]
> Thanks! The image that you sent is actually expired so would you be able to send it again LOL other than that, sounds great!

Ahh that's my bad! Hopefully this works:
![image](https://i.imgur.com/N1J1q3G.gif)

I will be sure to get working on the other issues, thank you! ❤️
