### ISSUE TITLE
Add encryption/decryption to Room

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#59]
We will need to add the most basic security to store our user data. For now, we will encrypt our data when we store them into room. [Here is a possible library we can use to achieve that](https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room)

**Comment by Manpreet-Bhatti** [comment]
@leowrites for the encryption of User data, do you want to encrypt every field in the User entity aside from the id?
Entity looks like this:
```kotlin
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 1,
    @TypeConverters(SymptomConverter::class)
    val symptomsToTrack: ArrayList<Symptom> = ArrayList(),
    @TypeConverters(DateConverter::class)
    val periodHistory: ArrayList<Date> = ArrayList(),
    val averagePeriodLength: Int = 0,
    val averageCycleLength: Int = 0,
    val daysSinceLastPeriod: Int = 0
    )
```

**Comment by leowrites** [comment]
Yes we need to encrypt everything

**Comment by leowrites** [comment]
@Manpreet-Bhatti 
In https://discuss.zetetic.net/t/sqlcipher-with-room-database/4535
> Are you creating your database from scratch, or does it already exist? If the latter, you will need to use sqlcipher_export(...)

It seems like the issue with nothing stored/read was that there was an existing unencrypted database. So deleting the virtual device and making a new one seems to make it work. One thing tho is I cannot open the database inside App Inspection anymore, which could be SQLcipher working, or something is wrong -- I will look into that more

**Comment by Manpreet-Bhatti** [comment]
@leowrites the reason you can't open the DB in app inspection is most likely due to it being properly encrypted. You're going to have to decrypt it using a DB viewer software like https://sqlitebrowser.org

**Comment by leowrites** [comment]
@Manpreet-Bhatti Yes, but otherwise I think it's working properly. The only issue would be for future debugging it would add complications to inspecting the db. Looking into Room a bit more it's saying the db is stored in folders only root has access to, which means no other apps or user can view the db, so I'm wondering if this added complexity of SQLCipher is worth it. We can try and submit the app without additional encryption and see what Google says.

**Comment by leowrites** [comment]
Closed to wait for Google Review
