### ISSUE TITLE
BUG - Dark Mode

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#77]
We need to consider accessibility for dark mode. Currently the contrast is messed up and we can't see a lot of the texts. 
<img width="377" alt="Screenshot 2023-03-09 at 11 28 43 AM" src="https://user-images.githubusercontent.com/75044178/224088572-1ea10e5f-0afe-48b0-a5a1-cbd1c81fa3ac.png">
<img width="377" alt="Screenshot 2023-03-09 at 11 28 55 AM" src="https://user-images.githubusercontent.com/75044178/224088614-f587eeac-8f2b-4b96-b8dd-5c0af9adf06e.png">
<img width="377" alt="Screenshot 2023-03-09 at 11 29 01 AM" src="https://user-images.githubusercontent.com/75044178/224088641-506dcfea-8bd3-40f8-bf4e-8919d0c54454.png">
<img width="377" alt="Screenshot 2023-03-09 at 11 29 08 AM" src="https://user-images.githubusercontent.com/75044178/224088669-cb443ef5-a448-4b37-96e4-db813305c4f2.png">

**Comment by madelahn** [comment]
Do you have any examples or maybe some guidance for what the dark mode should look like (e.g., different background)? Or is it primarily just making the white fonts black to make it easier to read?

**Comment by leowrites** [comment]
@madelahn Yes, essentially the dark mode should look exactly the same as the light mode.

**Comment by Manpreet-Bhatti** [comment]
Wouldn't changing
```kotlin
val colors = if (darkTheme) {
        DarkColorPalette
    } else {
        LightColorPalette
    }
```
to
```kotlin
val colors = LightColorPalette
```
in `Theme.kt` force Kotlin to use the light mode theme in our app?

**Comment by leowrites** [comment]
@Manpreet-Bhatti yup,, that seems to be the solution
