### ISSUE TITLE
BUG - Education page content hidden

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#85]
Please refer to the screenshot. Some of the content on the education page is hidden 
<img width="326" alt="Screenshot 2023-03-20 at 1 11 17 PM" src="https://user-images.githubusercontent.com/75044178/226416195-a684f1d8-79a5-4aa2-aabe-1e2ceab7c754.png">
<img width="326" alt="Screenshot 2023-03-20 at 1 09 57 PM" src="https://user-images.githubusercontent.com/75044178/226415946-92ef2c7d-ceac-4d64-823b-6e6a3001ede4.png">

**Comment by madelahn** [comment]
Would you prefer having the contents of the page scrollable or change the font size to fit the screen?

**Comment by leowrites** [comment]
> Would you prefer having the contents of the page scrollable or change the font size to fit the screen?

Let's go with scrollable!
